export const dataPost: DataPost[] = [
  {
    id: "1",
    username: "zackdesu",
    private: true,
    anonym: true,
    likes: 123,
    post: "Jika aku adalah sebuah burung, mungkin aku akan terbebas dari segala pengekangan yang saya alami.",
  },
  {
    id: "2",
    username: "zackdesu",
    private: true,
    anonym: true,
    likes: 123,
    post: "Jika aku adalah sebuah burung, mungkin aku akan terbebas dari segala pengekangan yang saya alami.",
  },
  {
    id: "3",
    username: "jofanctan",
    private: false,
    anonym: false,
    likes: 123,
    post: "Banyaknya tuntutan dan masalah-masalah belum terselesaikan.",
  },
  {
    id: "4",
    username: "kielll97",
    private: false,
    anonym: false,
    likes: 123,
    post: "Demam panggung...",
  },
  {
    id: "5",
    username: "zackdesu",
    private: false,
    anonym: false,
    likes: 123,
    post: "Jika aku adalah sebuah burung, mungkin aku akan terbebas dari segala pengekangan yang saya alami.",
  },
];
